# Generated by Django 4.1.7 on 2023-09-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=100, verbose_name="Название"
                    ),
                ),
                ("img", models.ImageField(upload_to="meal", verbose_name="Картинка")),
                (
                    "description",
                    models.TextField(max_length=999, verbose_name="Описание"),
                ),
            ],
        ),
    ]
