# Generated by Django 4.1.7 on 2023-09-20 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_case_titleforurl_alter_case_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="titleForURL",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Преобразование в URL",
            ),
        ),
        migrations.CreateModel(
            name="CaseBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Текст"), (2, "Одно изображение"), (3, "Слайдер")],
                        default=1,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "img_1",
                    models.ImageField(
                        blank=True, upload_to="caseBlocks", verbose_name="Изображение 1"
                    ),
                ),
                (
                    "img_2",
                    models.ImageField(
                        blank=True, upload_to="caseBlocks", verbose_name="Изображение 2"
                    ),
                ),
                (
                    "img_3",
                    models.ImageField(
                        blank=True, upload_to="caseBlocks", verbose_name="Изображение 3"
                    ),
                ),
                (
                    "img_4",
                    models.ImageField(
                        blank=True, upload_to="caseBlocks", verbose_name="Изображение 4"
                    ),
                ),
                (
                    "img_5",
                    models.ImageField(
                        blank=True, upload_to="caseBlocks", verbose_name="Изображение 5"
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Текст")),
                (
                    "fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.case"
                    ),
                ),
            ],
        ),
    ]
