# Generated by Django 4.1.7 on 2023-09-21 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_case_titleforurl_caseblock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="description",
        ),
    ]
