# Generated by Django 4.1.7 on 2023-09-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_remove_case_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="New",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=255, verbose_name="Название Новости"
                    ),
                ),
                ("date", models.DateTimeField(null=True, verbose_name="Время поста")),
                (
                    "img_1",
                    models.ImageField(
                        blank=True, upload_to="caseBlocks", verbose_name="Изображение 1"
                    ),
                ),
                (
                    "img_2",
                    models.ImageField(
                        blank=True, upload_to="caseBlocks", verbose_name="Изображение 2"
                    ),
                ),
                (
                    "img_3",
                    models.ImageField(
                        blank=True, upload_to="caseBlocks", verbose_name="Изображение 3"
                    ),
                ),
                (
                    "img_4",
                    models.ImageField(
                        blank=True, upload_to="caseBlocks", verbose_name="Изображение 4"
                    ),
                ),
                (
                    "img_5",
                    models.ImageField(
                        blank=True, upload_to="caseBlocks", verbose_name="Изображение 5"
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Текст")),
            ],
        ),
    ]
