# Generated by Django 4.1.7 on 2023-10-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_case_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="img_1",
            field=models.ImageField(
                blank=True, upload_to="case", verbose_name="Изображение 1"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="img_2",
            field=models.ImageField(
                blank=True, upload_to="case", verbose_name="Изображение 2"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="img_3",
            field=models.ImageField(
                blank=True, upload_to="case", verbose_name="Изображение 3"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="img_4",
            field=models.ImageField(
                blank=True, upload_to="case", verbose_name="Изображение 4"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="img_5",
            field=models.ImageField(
                blank=True, upload_to="case", verbose_name="Изображение 5"
            ),
        ),
        migrations.AlterField(
            model_name="new",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Время поста"
            ),
        ),
        migrations.AlterField(
            model_name="new",
            name="img_1",
            field=models.ImageField(
                blank=True, upload_to="news", verbose_name="Изображение 1"
            ),
        ),
        migrations.AlterField(
            model_name="new",
            name="img_2",
            field=models.ImageField(
                blank=True, upload_to="news", verbose_name="Изображение 2"
            ),
        ),
        migrations.AlterField(
            model_name="new",
            name="img_3",
            field=models.ImageField(
                blank=True, upload_to="news", verbose_name="Изображение 3"
            ),
        ),
        migrations.AlterField(
            model_name="new",
            name="img_4",
            field=models.ImageField(
                blank=True, upload_to="news", verbose_name="Изображение 4"
            ),
        ),
        migrations.AlterField(
            model_name="new",
            name="img_5",
            field=models.ImageField(
                blank=True, upload_to="news", verbose_name="Изображение 5"
            ),
        ),
    ]
