# Generated by Django 4.1.7 on 2023-11-15 15:39

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_case_img_1_case_img_2_case_img_3_case_img_4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="new",
            name="titleNewForURL",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Преобразование в URL",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="img",
            field=models.ImageField(
                upload_to=main.models.case_obl_directory_path, verbose_name="Обложка"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="img_1",
            field=models.ImageField(
                blank=True,
                upload_to=main.models.case_directory_path,
                verbose_name="Изображение 1",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="img_2",
            field=models.ImageField(
                blank=True,
                upload_to=main.models.case_directory_path,
                verbose_name="Изображение 2",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="img_3",
            field=models.ImageField(
                blank=True,
                upload_to=main.models.case_directory_path,
                verbose_name="Изображение 3",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="img_4",
            field=models.ImageField(
                blank=True,
                upload_to=main.models.case_directory_path,
                verbose_name="Изображение 4",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="img_5",
            field=models.ImageField(
                blank=True,
                upload_to=main.models.case_directory_path,
                verbose_name="Изображение 5",
            ),
        ),
        migrations.DeleteModel(
            name="CaseBlock",
        ),
    ]
